services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: calc-hub-back
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/calc_hub
      JWT_ACCESS_SECRET: change_me_access_secret
      JWT_REFRESH_SECRET: change_me_refresh_secret
      JWT_ACCESS_TTL_SEC: 900
      JWT_REFRESH_TTL_SEC: 2592000
      CORS_ORIGINS: http://localhost:3000,http://localhost:5173,http://localhost:8080,http://localhost:8081
    depends_on:
      - postgres
      - redis
    ports:
      - '3000:3000'
    command: sh -c "node dist/main.js"

  postgres:
    image: postgres:16-alpine
    container_name: calc-hub-postgres
    environment:
      POSTGRES_DB: calc_hub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: calc-hub-redis
    ports:
      - '6379:6379'

volumes:
  postgres_data:
