// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const viteEnv = (import.meta as ImportMeta | undefined)?.env;
const SUPABASE_URL = viteEnv?.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = viteEnv?.VITE_SUPABASE_PUBLISHABLE_KEY;
const nodeEnv =
  typeof globalThis !== "undefined" && "process" in globalThis
    ? (globalThis as { process?: { env?: Record<string, string | undefined> } }).process?.env
    : undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const resolvedSupabaseUrl = SUPABASE_URL ?? nodeEnv?.NEXT_PUBLIC_SUPABASE_URL ?? "";
const resolvedSupabaseKey =
  SUPABASE_PUBLISHABLE_KEY ?? nodeEnv?.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ?? "";
const hasSupabaseConfig = Boolean(resolvedSupabaseUrl && resolvedSupabaseKey);

const supabaseUrl = hasSupabaseConfig
  ? resolvedSupabaseUrl
  : "https://placeholder.supabase.co";
const supabaseKey = hasSupabaseConfig
  ? resolvedSupabaseKey
  : "placeholder-anon-key";

if (!hasSupabaseConfig && typeof window !== "undefined") {
  console.warn(
    "[supabase] Missing SUPABASE env vars. Using placeholder client. Set VITE_SUPABASE_URL/VITE_SUPABASE_PUBLISHABLE_KEY or NEXT_PUBLIC_* equivalents.",
  );
}

export const supabase = createClient<Database>(supabaseUrl, supabaseKey, {
  auth: {
    storage: typeof window !== "undefined" ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});