import type { CpaOffer } from "./CpaBlock";

/** Офферы для страниц кредитных калькуляторов */
export const CREDIT_OFFERS: CpaOffer[] = [
  {
    id: "tinkoff-credit",
    bank: "Т-Банк",
    logo: "Т",
    logoColor: "bg-yellow-400/20 text-yellow-600 dark:text-yellow-400",
    rate: "от 7,9%",
    rateLabel: "годовых",
    term: "До 5 лет",
    amount: "До 5 000 000 ₽",
    badge: "Популярный",
    badgeVariant: "default",
    highlight: true,
    features: [
      "Решение за 2 минуты онлайн",
      "Без справок о доходах",
      "Досрочное погашение без штрафов",
    ],
    cta: "Оформить кредит",
    url: "https://tinkoff.ru/loans/",
  },
  {
    id: "sber-credit",
    bank: "Сбербанк",
    logo: "С",
    logoColor: "bg-green-500/20 text-green-700 dark:text-green-400",
    rate: "от 9,9%",
    rateLabel: "годовых",
    term: "До 7 лет",
    amount: "До 10 000 000 ₽",
    badge: "Надёжный",
    badgeVariant: "secondary",
    highlight: false,
    features: [
      "Ставка ниже при наличии зарплатной карты",
      "Онлайн через СберБанк Онлайн",
      "Страхование жизни — по желанию",
    ],
    cta: "Узнать условия",
    url: "https://sberbank.ru/ru/person/credits/",
  },
  {
    id: "alfa-credit",
    bank: "Альфа-Банк",
    logo: "А",
    logoColor: "bg-red-500/20 text-red-600 dark:text-red-400",
    rate: "от 10,9%",
    rateLabel: "годовых",
    term: "До 7 лет",
    amount: "До 7 500 000 ₽",
    badge: "Быстро",
    badgeVariant: "outline",
    highlight: false,
    features: [
      "Одобрение за 1 минуту",
      "Перевод средств в день обращения",
      "Без обеспечения и поручителей",
    ],
    cta: "Получить деньги",
    url: "https://alfabank.ru/get-money/",
  },
];

/** Офферы для ипотечных страниц */
export const MORTGAGE_OFFERS: CpaOffer[] = [
  {
    id: "sber-mortgage",
    bank: "Сбербанк",
    logo: "С",
    logoColor: "bg-green-500/20 text-green-700 dark:text-green-400",
    rate: "от 10,7%",
    rateLabel: "годовых",
    term: "До 30 лет",
    amount: "До 100 000 000 ₽",
    badge: "Господдержка",
    badgeVariant: "default",
    highlight: true,
    features: [
      "Семейная ипотека от 6%",
      "Первоначальный взнос от 15%",
      "Полностью онлайн через ДомКлик",
    ],
    cta: "Рассчитать ипотеку",
    url: "https://domclick.ru/ipoteka",
  },
  {
    id: "vtb-mortgage",
    bank: "ВТБ",
    logo: "В",
    logoColor: "bg-blue-500/20 text-blue-600 dark:text-blue-400",
    rate: "от 11,2%",
    rateLabel: "годовых",
    term: "До 30 лет",
    amount: "До 60 000 000 ₽",
    badge: "Новостройки",
    badgeVariant: "secondary",
    highlight: false,
    features: [
      "Ставка 6% для семей с детьми",
      "Первоначальный взнос от 10%",
      "IT-ипотека по льготной ставке",
    ],
    cta: "Подать заявку",
    url: "https://vtb.ru/personal/ipoteka/",
  },
  {
    id: "alfa-mortgage",
    bank: "Альфа-Банк",
    logo: "А",
    logoColor: "bg-red-500/20 text-red-600 dark:text-red-400",
    rate: "от 11,5%",
    rateLabel: "годовых",
    term: "До 30 лет",
    amount: "До 70 000 000 ₽",
    badge: "Без лишних справок",
    badgeVariant: "outline",
    highlight: false,
    features: [
      "Решение за 1–3 рабочих дня",
      "Рефинансирование ипотеки других банков",
      "Онлайн-оформление без посещения офиса",
    ],
    cta: "Узнать ставку",
    url: "https://alfabank.ru/get-money/mortgage/",
  },
];

/** Офферы для страницы рефинансирования */
export const REFINANCE_OFFERS: CpaOffer[] = [
  {
    id: "tinkoff-refi",
    bank: "Т-Банк",
    logo: "Т",
    logoColor: "bg-yellow-400/20 text-yellow-600 dark:text-yellow-400",
    rate: "от 7,9%",
    rateLabel: "годовых",
    term: "До 5 лет",
    amount: "До 5 000 000 ₽",
    badge: "Лучшая ставка",
    badgeVariant: "default",
    highlight: true,
    features: [
      "Объединение до 10 кредитов",
      "Снижение ежемесячного платежа",
      "Решение за 2 минуты",
    ],
    cta: "Рефинансировать",
    url: "https://tinkoff.ru/loans/refinancing/",
  },
  {
    id: "sber-refi",
    bank: "Сбербанк",
    logo: "С",
    logoColor: "bg-green-500/20 text-green-700 dark:text-green-400",
    rate: "от 9,9%",
    rateLabel: "годовых",
    term: "До 7 лет",
    amount: "До 5 000 000 ₽",
    badge: "Надёжно",
    badgeVariant: "secondary",
    highlight: false,
    features: [
      "Рефинансирование кредитов других банков",
      "Ставка 9,9% при зарплатном проекте",
      "Онлайн-заявка без визита в офис",
    ],
    cta: "Снизить ставку",
    url: "https://sberbank.ru/ru/person/credits/refinancing/",
  },
  {
    id: "vtb-refi",
    bank: "ВТБ",
    logo: "В",
    logoColor: "bg-blue-500/20 text-blue-600 dark:text-blue-400",
    rate: "от 10,4%",
    rateLabel: "годовых",
    term: "До 7 лет",
    amount: "До 7 000 000 ₽",
    badge: "Крупные суммы",
    badgeVariant: "outline",
    highlight: false,
    features: [
      "Погашение до 10 действующих кредитов",
      "Суммы от 100 000 до 7 000 000 ₽",
      "Досрочное погашение без комиссий",
    ],
    cta: "Оставить заявку",
    url: "https://vtb.ru/personal/kredit/refinansirovanie/",
  },
];
